# Generated by Django 3.2.13 on 2022-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
