# Generated by Django 3.2.13 on 2022-09-02 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_customer_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
    ]
