# Generated by Django 3.2.13 on 2022-09-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_invitee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='administration.customer'),
        ),
        migrations.AddConstraint(
            model_name='invitee',
            constraint=models.UniqueConstraint(fields=('email', 'customer'), name='unique_email'),
        ),
    ]
