# Generated by Django 3.2.13 on 2022-09-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_migrate_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='admins',
        ),
    ]
