# Generated by Django 3.2.13 on 2022-09-07 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_customer_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
