# Generated by Django 3.2.13 on 2022-09-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_customer_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='email_domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
