# Generated by Django 3.2.13 on 2022-09-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_domains',
        ),
    ]
