# Generated by Django 3.2.13 on 2022-09-09 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_remove_customer_email_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
