# Generated by Django 3.2.13 on 2022-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20220916_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
