# Generated by Django 3.2.13 on 2022-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_migrate_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
