# Generated by Django 3.2.13 on 2022-08-02 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('claims_number', models.IntegerField(default=0)),
                ('pct_pos_consensus', models.FloatField(default=1)),
                ('pct_neg_consensus', models.FloatField(default=1)),
                ('type', models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con')], default='PRO', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='conversations.claim')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='conversations.conversation')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('conversation', 'claim', 'type', 'tag'), name='unique_summary'),
        ),
    ]
