# Generated by Django 3.2.13 on 2022-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_summary_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con'), ('ANS', 'Ans')], default='PRO', max_length=3),
        ),
    ]
