# Generated by Django 3.2.13 on 2022-08-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_fill_themes'),
        ('scheduling', '0003_alter_summary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.topic'),
        ),
    ]
