# Generated by Django 3.2.13 on 2022-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_migrate_topics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summary',
            name='unique_summary',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='tag',
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('conversation', 'claim', 'type', 'topic'), name='unique_summary'),
        ),
    ]
