# Generated by Django 3.2.13 on 2022-08-12 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_auto_20220812_0352'),
        ('scheduling', '0006_auto_20220812_0347'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summary',
            name='unique_summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.tag'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('conversation', 'claim', 'type', 'tag'), name='unique_summary'),
        ),
    ]
