# Generated by Django 3.2.13 on 2022-08-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20220812_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='topic',
        ),
    ]
