# Generated by Django 3.2.13 on 2022-09-02 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_create_conversation_surveys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationsurvey',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='conversationsurveyvote',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='conversationsurveyvote',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
