# Generated by Django 3.2.13 on 2022-08-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='administration.customer'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='administration.customer'),
        ),
        migrations.AddField(
            model_name='tag',
            name='customers',
            field=models.ManyToManyField(blank=True, to='administration.Customer'),
        ),
        migrations.AddField(
            model_name='vote',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='administration.customer'),
        ),
    ]
