# Generated by Django 3.2.13 on 2022-08-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20220802_0340'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claim',
            name='check_claim_constraints',
        ),
    ]
