# Generated by Django 3.2.13 on 2022-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_claim_check_claim_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('open_ended', True), ('parent__isnull', True), ('root_claim__isnull', True), ('top_relation', 0), ('type', 'ANS')), models.Q(('open_ended', True), ('parent__isnull', False), ('root_claim__isnull', False), ('top_relation__in', [-1, 1]), ('type__in', ['CON', 'PRO'])), models.Q(('open_ended', False), ('parent__isnull', False), ('root_claim__isnull', True), ('top_relation__in', [-1, 1]), ('type__in', ['CON', 'PRO'])), models.Q(('open_ended', False), ('parent__isnull', True), ('root_claim__isnull', True), ('top_relation', 1), ('type', 'PRO')), models.Q(('open_ended', False), ('parent__isnull', True), ('root_claim__isnull', True), ('top_relation', -1), ('type', 'CON')), _connector='OR'), name='check_claim_constraints'),
        ),
    ]
