# Generated by Django 3.2.13 on 2022-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_claim_check_claim_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
