# Generated by Django 3.2.13 on 2022-08-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
    ]
