# Generated by Django 3.2.13 on 2022-08-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_customer_categories'),
        ('conversations', '0006_remove_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number_used', models.IntegerField(default=1)),
                ('customers', models.ManyToManyField(blank=True, to='administration.Customer')),
            ],
            options={
                'ordering': ('-number_used', 'name'),
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='claim_topics', to='conversations.Topic'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topics',
            field=models.ManyToManyField(blank=True, to='conversations.Topic'),
        ),
    ]
