# Generated by Django 3.2.13 on 2022-08-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_auto_20220812_0347'),
        ('conversations', '0008_fill_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
