# Generated by Django 3.2.13 on 2022-08-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_remove_summary_topic'),
        ('conversations', '0011_migrate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
