"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import boto3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '...'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.environ.get('ENV') != 'production')

ALLOWED_HOSTS = [
    'localhost',
    '2e89-47-229-245-157.ngrok.io'
]

if os.environ.get('ENV') == 'staging':
    ALLOWED_HOSTS.append('api.staging.insight.getmotivee.com')
elif os.environ.get('ENV') == 'production':
    ALLOWED_HOSTS.append('api.insight.getmotivee.com')

AUTH_USER_MODEL = 'login.User'
# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ebhealthcheck.apps.EBHealthCheckConfig',
    'django_extensions',
    'rest_framework',
    'login',
    'conversations',
    'scheduling',
    'administration',
    'surveys',
    'stats',
    'payment',
    'slack',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

if 'RDS_HOSTNAME' in os.environ:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if os.environ.get('ENV') == 'staging':
    CORS_ORIGIN_WHITELIST = [
        'http://localhost:3000',
        'https://staging.insight.getmotivee.com',
    ]
elif os.environ.get('ENV') == 'production':
    CORS_ORIGIN_WHITELIST = [
        'https://insight.getmotivee.com',
    ]
else:
    CORS_ORIGIN_WHITELIST = [
        'http://localhost:3000',
    ]


# print('cors', CORS_ORIGIN_WHITELIST)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'login.authentication.FirebaseAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'administration.permissions.CustomerAccessPermission',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'administration.filters.CustomerFilterBackend'
    ],
    'DEFAULT_PAGINATION_CLASS': 'app.pagination.Pagination',
    'PAGE_SIZE': 30
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AWS_S3_REGION_NAME = 'us-east-1'

boto3_logs_client = boto3.client(
    'logs',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_S3_REGION_NAME
)

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


LOGGING = {
    'version': 1,
    "disable_existing_loggers": False,
    "formatters": {
        "aws": {
            "format": '%(levelname)s - %(pathname)s \n %(funcName)s:%(lineno)s \n %(message)s',
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "watchtower": {
            "level": "ERROR",
            "boto3_client": boto3_logs_client,
            "class": "watchtower.CloudWatchLogHandler",
            "log_group_name": "Django_logs",
            # Different stream for each environment
            "log_stream_name": os.environ.get('ENV', 'localhost'),
            "formatter": "aws",
        },
        "console": {"class": "logging.StreamHandler", "formatter": "aws", },
    },
    "loggers": {
        # Use this logger to send data just to Cloudwatch
        "watchtower": {
            "level": 'ERROR', "handlers": ["watchtower"], "propogate": True, 
        }
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if os.environ.get('ENV') == 'production':
    FIREBASE_CONFIG = os.path.join(BASE_DIR, 'firebase-config-production.json')
else:
    FIREBASE_CONFIG = os.path.join(BASE_DIR, 'firebase-config-staging.json')


ASGI_APPLICATION = "app.asgi.application"
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}


# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_BROKER_URL = 'sqs://{}:{}@'.format(
#     AWS_ACCESS_KEY_ID,
#     AWS_SECRET_ACCESS_KEY
# )
# # Due to error on lib region N Virginia is used temporarily. please set it on Ireland "eu-west-1" after fix.
# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     "region": AWS_S3_REGION_NAME,
#     'queue_name_prefix': 'django_app-{}-'.format(os.environ.get('ENV', 'localhost')),
#     'visibility_timeout': 360,
#     'polling_interval': 1
# }
