# Generated by Django 3.2.13 on 2022-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220802_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
