# Generated by Django 3.2.13 on 2022-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_customer_email_domains'),
        ('login', '0003_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customers',
            field=models.ManyToManyField(blank=True, to='administration.Customer'),
        ),
    ]
