# Generated by Django 3.2.13 on 2022-09-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_customer_email_domains'),
        ('login', '0005_migrate_to_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_categories', to='administration.customer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.AddConstraint(
            model_name='usercategories',
            constraint=models.UniqueConstraint(fields=('user', 'customer'), name='unique_category'),
        ),
    ]
