# Generated by Django 3.2.13 on 2022-09-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_customer_email_domains'),
        ('login', '0007_migrate_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_users', to='administration.customer'),
        ),
    ]
