# Generated by Django 3.2.13 on 2022-09-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_fill_empty_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
    ]
